In [ ]:
import numpy as np

In [ ]:
arr1=np.empty((2,3))
arr2=np.array([[10,2,3],[23,45,67]])

In [ ]:
print(arr2)

[[10  2  3]
 [23 45 67]]


In [ ]:
arr3=np.ones((2,3))
print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr4=np.zeros((2,3),dtype=int)
print(arr4)

[[0 0 0]
 [0 0 0]]


In [ ]:
np.random.random((2,2))

array([[0.49258584, 0.4444419 ],
       [0.26251619, 0.1238045 ]])

In [ ]:
var2=np.empty(4)
var2[0]=5.67
var2[1]=2
var2[2]=56
var2[2]=304
print(var2)

[5.67000000e+00 2.00000000e+00 3.04000000e+02 1.23804495e-01]


In [ ]:
print(var2.shape)

(4,)


In [ ]:
print(var2.size)

4


In [ ]:
var3=np.empty((2,3))
var3[0][0]=5.67
var3[0][1]=2
var3[0][2]=56
var3[1][0]=0.09
var3[1][1]=132
var3[1][2]=1056
print(var3)


[[5.670e+00 2.000e+00 5.600e+01]
 [9.000e-02 1.320e+02 1.056e+03]]


In [ ]:
print(var3.shape)

(2, 3)


In [ ]:
var3=np.empty((2,3),dtype=int)
var3[0][0]=5.67
var3[0][1]=2
var3[0][2]=56
var3[1][0]=0.09
var3[1][1]=132
var3[1][2]=1056
print(var3)


[[   5    2   56]
 [   0  132 1056]]


In [ ]:
print(var3[1])

[   0  132 1056]


In [ ]:
print(var3[[0,1]])

[[   5    2   56]
 [   0  132 1056]]


In [ ]:
print(var3[:,2])

[  56 1056]


In [ ]:
print(var3[:,[1,2]])

[[   2   56]
 [ 132 1056]]


In [ ]:
print(var3[1][2])

1056


In [ ]:
print(var3[1,2])

1056


In [ ]:
print(np.transpose(var3))

[[   5    0]
 [   2  132]
 [  56 1056]]


In [ ]:
print(var3.reshape(3,2))

[[   5    2]
 [  56    0]
 [ 132 1056]]


In [ ]:
arr1=np.empty((2,3),dtype=int)
arr1[0][0]=5.67
arr1[0][1]=2
arr1[0][2]=56
arr1[1][0]=0.09
arr1[1][1]=132
arr1[1][2]=1056
print(arr1)


[[   5    2   56]
 [   0  132 1056]]


In [ ]:
arr2=np.empty((1,3),dtype=int)
arr2[0][0]=37
arr2[0][1]=2.193
arr2[0][2]=5609
print(arr2)

[[  37    2 5609]]


In [ ]:
arr_concat=np.concatenate((arr1,arr2),axis=0)
print(arr_concat)

[[   5    2   56]
 [   0  132 1056]
 [  37    2 5609]]


In [ ]:
print(arr2.min())

2


In [ ]:
arr2.max()

5609

In [ ]:
arr2.cumsum()

array([  37,   39, 5648])

In [ ]:
arr2.mean()

1882.6666666666667

In [ ]:
arr2.std()

2634.9543112210163

In [ ]:
from numpy import pi

In [ ]:
array1=np.array([30,60,90])
np.sin(array1*np.pi/180)

array([0.5      , 0.8660254, 1.       ])

In [ ]:
arr2=np.array([67.07,88.10,34,231.67,0.934])
print(arr2)

[ 67.07   88.1    34.    231.67    0.934]


In [ ]:
np.around(arr2)

array([ 67.,  88.,  34., 232.,   1.])

In [ ]:
np.around(arr2,decimals=2)

array([ 67.07,  88.1 ,  34.  , 231.67,   0.93])

In [ ]:
np.floor(arr2)

array([ 67.,  88.,  34., 231.,   0.])

In [ ]:
np.ceil(arr2)

array([ 68.,  89.,  34., 232.,   1.])

In [ ]:
arr2=np.arange(6,dtype=int).reshape(2,3)

In [ ]:
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
np.add(arr1,arr2)

array([[   5,    3,   58],
       [   3,  136, 1061]])

In [ ]:
np.subtract(arr1,arr2)

array([[   5,    1,   54],
       [  -3,  128, 1051]])

In [ ]:
np.multiply(arr1,arr2)

array([[   0,    2,  112],
       [   0,  528, 5280]])

In [ ]:
np.divide(arr2,arr1)

<ipython-input-41-6a0bd0e0205e>:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(arr2,arr1)


array([[0.        , 0.5       , 0.03571429],
       [       inf, 0.03030303, 0.00473485]])

In [ ]:
np.power(arr1,2)

array([[     25,       4,    3136],
       [      0,   17424, 1115136]])

In [ ]:
np.mod(arr2,arr1)

<ipython-input-43-acd918db7191>:1: RuntimeWarning: divide by zero encountered in remainder
  np.mod(arr2,arr1)


array([[0, 1, 2],
       [0, 4, 5]])

In [ ]:
np.remainder(arr2,arr1)

<ipython-input-44-3e2449219b99>:1: RuntimeWarning: divide by zero encountered in remainder
  np.remainder(arr2,arr1)


array([[0, 1, 2],
       [0, 4, 5]])

In [ ]:
a=np.array([[21,7,14],[19,40,8]])
a

array([[21,  7, 14],
       [19, 40,  8]])

In [ ]:
np.sort(a)

array([[ 7, 14, 21],
       [ 8, 19, 40]])

In [ ]:
np.sort(a,axis=0)

array([[19,  7,  8],
       [21, 40, 14]])

In [ ]:
np.sort(a,axis=1)

array([[ 7, 14, 21],
       [ 8, 19, 40]])

In [ ]:
np.where(a>13)

(array([0, 0, 1, 1]), array([0, 2, 0, 1]))

In [ ]:
print(a[np.where(a>13)])

[21 14 19 40]


In [ ]:
np.mean(a)

18.166666666666668

In [ ]:
np.mean(a,axis=1)

array([14.        , 22.33333333])

In [ ]:
np.mean(a,axis=0)

array([20. , 23.5, 11. ])

In [ ]:
np.median(a)

16.5

In [ ]:
np.median(a,axis=1)

array([14., 19.])

In [ ]:
np.median(a,axis=0)

array([20. , 23.5, 11. ])

In [ ]:
np.std(a)

11.036555420762202

In [ ]:
np.var(a)

121.80555555555554